version: 3.5 ;

services:

  db_oms:
    container_name: db_oms
    ports:
      - "5432:5432" 
    environment:
      PG_DATA: /var/lib/postgresql/data
    image: postgres:14.3-alpine3.16
    env_file:
      - development.env
    volumes:
      - oms_data:/var/lib/postgresql/data
    restart: always
  
volumes:
  oms_data:

  