version: 3.5 ;

services:
  app_oms:
    container_name: app_oms
    build:
      context: . 
      dockerfile: Dockerfile

    env_file:
      - development.env
    
    volumes:
      - /C/Users/User/.vscode/Backend/OMS/order-managament-server:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229

    command: npm run start:dev
    depends_on:
      - db_oms
    restart: always

  db_oms:
    container_name: db_oms
    ports:
      - "5432:5432" 
    environment:
      PG_DATA: /var/lib/postgresql/data
    image: postgres:14.3-alpine3.16
    env_file:
      - development.env
    volumes:
      - oms_data:/var/lib/postgresql/data
    restart: always
  
volumes:
  oms_data:

  