name: Node.js CI with Docker Compose

on:
  push:
    branches: [ "postgre" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker and docker-compose
      run: |
        sudo apt-get update
        sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Start services with docker-compose
      run: docker-compose up -d

  build-and-run:
    needs: docker-setup  
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.10.0
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run start
    - run: npm run start:prod
    - run: npm run format
    - run: npm run lint
    - run: npm test


    - name: Stop services with docker-compose
      run: docker-compose down
